# mosquitto.conf — Konfigurasi MQTT Broker Mosquitto 2.0
# Role 4: Environment & IoT Layer

listener 1883
allow_anonymous false

# File password: generate dengan
#   mosquitto_passwd -c /mosquitto/config/passwd iot_device
password_file /mosquitto/config/passwd

# Logging
log_type all
log_dest stdout

# Persistence
persistence true
persistence_location /mosquitto/data/

# Max connections (sesuaikan dengan jumlah sensor)
max_connections 100

# QoS max
max_qos 2
