apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-ml-hpa
  namespace: smartcity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-ml
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70   # scale up kalau CPU > 70%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30   # tunggu 30 detik sebelum scale up
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60            # tambah max 2 pod per menit
    scaleDown:
      stabilizationWindowSeconds: 120  # tunggu 2 menit sebelum scale down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60            # kurangi max 1 pod per menit