apiVersion: v1
kind: Secret

metadata:
  name: smart-city-secret
  namespace: smartcity

type: Opaque

stringData:

  # MySQL
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_USER: "env_user"
  MYSQL_PASSWORD: "env_secret"

  # JWT
  JWT_ACCESS_SECRET: "accessrahasia_super_secret_min_32_chars"

  # RabbitMQ
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
